### ISSUE TITLE
How can I change it to only one column?

### ISSUE THREAD

**Issue by dterrey** [dhondta/tex-course-index#3]

**Comment by dhondta** [comment]
Hi @dterrey
See `main.tex`, lines 83 to 92 ; this block redefines `theindex` environment with the `begin` and `end` delimiters of `multicols` at lines 91 and 92. You can remove these delimiters and it should do the trick.

**Comment by flomch96** [comment]
Hi @dhondta 
I am new latex. I followed your tutorial on how to compile file but i keep receiving the following error after the  Click on Quick Build to compile :
Error : could not start the command : makeindex "main".idx -s lib/std.ist
Do you have any idea about the cause, i use texmaker also.

**Comment by dhondta** [comment]
Hi @flomch96 !
Please check the issue's title ; what you are asking for is completely unrelated. Please open a new issue for future cases.
This error mostly likely occurs because TeXmaker cannot find `makeindex`. Try specifying the full path to `makeindex` (you can find it easily with the OS command `which makeindex` ; in my case, it is `/usr/bin/makeindex`) and retry the compilation...
